agent: 'IQL'
# dataset: '/home/franka/dev/kathyz/hand_dapg/dapg/demonstrations/replayed_door-v0_demos.pickle'
dataset: '/home/prl/data/morel_pushing-lid-delta-025smoothed.pkl'
learner:
  use_gpu: True
  batch_size: 1024
  actor_learning_rate: 0.0001
  critic_learning_rate: 0.0003
  tau: 0.005
  lam: 1.0
  n_action_samples: 1 #?
  update_actor_interval: 1
  scaler: 'standard'
  action_scaler: 'min_max'

training:
  n_steps: 10000000
